const regions = [
  { key: "AT", title: "Austria" },
  { key: "BE", title: "Belgium" },
  { key: "BG", title: "Bulgaria" },
  { key: "CZ", title: "Czech Republic" },
  { key: "DK", title: "Denmark" },
  { key: "DE", title: "Germany" },
  { key: "EE", title: "Estonia" },
  { key: "IE", title: "Ireland" },
  { key: "EL", title: "Greece" },
  { key: "ES", title: "Spain" },
  { key: "FR", title: "France" },
  { key: "HR", title: "Croatia" },
  { key: "IT", title: "Italy" },
  { key: "CY", title: "Cyprus" },
  { key: "LV", title: "Latvia" },
  { key: "LT", title: "Lithuania" },
  { key: "LU", title: "Luxembourg" },
  { key: "HU", title: "Hungary" },
  { key: "MT", title: "Malta" },
  { key: "NL", title: "Netherlands" },
  { key: "NO", title: "Norway" },
  { key: "PL", title: "Poland" },
  { key: "PT", title: "Portugal" },
  { key: "RO", title: "Romania" },
  { key: "SI", title: "Slovenia" },
  { key: "SK", title: "Slovakia" },
  { key: "FI", title: "Finland" },
  { key: "SE", title: "Sweden" },
  { key: "AUSTRALIA", title: "Australia" },
  { key: "ARGENTINA", title: "Argentina" },
  { key: "BRAZIL", title: "Brazil" },
  { key: "CANADA", title: "Canada" },
  { key: "INDIA", title: "India" },
  { key: "INDONESIA", title: "Indonesia" },
  { key: "JAPAN", title: "Japan" },
  { key: "MEXICO", title: "Mexico" },
  { key: "RUSSIA", title: "Russia" },
  { key: "SAUDI_ARABIA", title: "Saudi Arabia" },
  { key: "SOUTH_AFRICA", title: "South Africa" },
  { key: "SOUTH_KOREA", title: "South Korea" },
  { key: "TURKEY", title: "Turkey" },
  { key: "UK", title: "United Kingdom" },
  { key: "EU_DEFAULT", title: "EU (default average)" },
  { key: "US_DEFAULT", title: "US (default average)" },
  { key: "CHINA_DEFAULT", title: "China (default average)" },
  { key: "WORLD_DEFAULT", title: "World (default average)" }
];

export default regions;
